version: "3"

services:
  app:
    networks:
      - default
    build: .
    container_name: simulador
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  default:
    name: kafka_default
